server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.hmtl;

    # Vue Router History Mode
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Spring Boot API
    location /api/ {
        proxy_pass http://feldbuch-app:8080;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # SSE
        proxy_buffering off;
        proxy_cache off;
    }
}