spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/feldbuch
    username: root
    password: flflflfl1

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 012345678901234567890123456789012345678901234567890123456789abcd
  access-token-expiration: 1800000

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  model: gpt-4.1-nano
