name: CI

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Test backend
        run: |
          ./gradlew clean test \
            --tests "io.github.kaltz.feldbuch.FeldbuchApplicationTests" \
            || true

          echo "===== BeanDefinitionOverrideException ====="

          grep -R -B 5 -A 15 \
            "BeanDefinitionOverrideException" \
            build/test-results/test/ || true

          exit 1

      - name: Show bean override error
        if: failure()
        run: |
          grep -n -A 40 -B 10 "BeanDefinitionOverrideException" test.log || true

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build